version: "3.2"
services:
  satis:
    image: ypereirareis/docker-satis:5.0
    build: ./
    container_name: satis
    hostname: satis
    env_file:
      - .env
    networks:
      - webproxy
    volumes:
      - "/var/tmp/composer:/var/www/.composer"
      - "~/.ssh/id_rsa:/var/tmp/id"
      - "./parameters.satisfy.yml:/satisfy/app/config/parameters.yml"
      - "./satis.json:/satisfy/satis.json"
    environment:
      PRIVATE_REPO_DOMAIN_LIST: bitbucket.org gitlab.com github.com
      CRONTAB_FREQUENCY: "*/1 * * * *"
      VIRTUAL_HOST: ${VHOST}

networks:
  webproxy:
    external:
      name: ${PROXY_NETWORK}