version: "3.2"
services:
  satis:
    image: ypereirareis/docker-satis:${IMAGE_VERSION:-5.4}
    build: ./
    container_name: satis
    hostname: satis
    ports:
      - "80:80"
    networks:
      - webproxy
    volumes:
      - "/var/tmp/composer:/var/www/.composer"
      - "~/.ssh/nopass_rsa:/var/tmp/id"
      - "./config/parameters.yml:/satisfy/config/parameters.yml"
      - "./config/satis.json:/satisfy/config/satis.json"
    environment:
      PRIVATE_REPO_DOMAIN_LIST: bitbucket.org gitlab.com github.com bitbucket.ruhmesmeile.tools:7999
      CRONTAB_FREQUENCY: "-1"
      VIRTUAL_HOST: satis.machine

networks:
  webproxy:
    external:
      name: ${PROXY_NETWORK}
