services:
  _defaults:
    public: false

  Playbloom\Satisfy\Command\RebuildCommand:
    autowire: true
    tags:
      - { name: console.command }

  Playbloom\Satisfy\Service\Manager:
    autowire: true
    public: true
    bind:
      Symfony\Component\Lock\Lock: "@lock.satis"

  satisfy.manager:
    alias: Playbloom\Satisfy\Service\Manager

  Playbloom\Satisfy\Persister\FilePersister:
    autowire: true
    arguments:
      $filename: "%satis_filename%"
      $logPath: "%satis_log_path%"

  satisfy.persister.file:
    alias: Playbloom\Satisfy\Persister\FilePersister

  Playbloom\Satisfy\Persister\JsonPersister:
    class: Playbloom\Satisfy\Persister\JsonPersister
    public: false
    arguments:
      - "@satisfy.persister.file"
      - "@serializer"
      - "Playbloom\\Satisfy\\Model\\Configuration"

  Playbloom\Satisfy\Persister\ConfigurationNormalizer:
    autowire: true
    tags:
      - { name: serializer.normalizer, priority: 1000 }

  satisfy.persister.json:
    alias: Playbloom\Satisfy\Persister\JsonPersister

  satisfy.processor.lock_processor:
    alias: Playbloom\Satisfy\Service\LockProcessor

  Playbloom\Satisfy\Service\LockProcessor:
    autowire: true
    public: true

  satisfy.process.factory:
    alias: Playbloom\Satisfy\Process\ProcessFactory

  Playbloom\Satisfy\Process\ProcessFactory:
    autowire: true
    arguments:
      $rootPath: "%kernel.project_dir%"
      $composerHome: "%composer.home%"

  Playbloom\Satisfy\Runner\SatisBuildRunner:
    autowire: true
    public: true
    arguments:
      $satisFilename: "%satis_filename%"
    bind:
      Symfony\Component\Lock\Lock: "@lock.build"
    tags:
      - { name: kernel.event_listener, event: Playbloom\Satisfy\Event\BuildEvent, method: onBuild }
      - { name: kernel.event_listener, event: Playbloom\Satisfy\Event\BuildRepoEvent, method: onBuildRepo }

  ### Webhook handlers
  Playbloom\Satisfy\Webhook\BitbucketWebhook:
    autowire: true
    public: true

  Playbloom\Satisfy\Webhook\GithubWebhook:
    autowire: true
    public: true
    arguments:
      $secret: "%github.secret%"

  Playbloom\Satisfy\Webhook\GitlabWebhook:
    autowire: true
    public: true
    arguments:
      $secret: "%gitlab.secret%"
      $autoAdd: "%gitlab.auto_add_repo%"
      $autoAddType: "%gitlab.auto_add_repo_type%"

  Playbloom\Satisfy\Validator\EnvValidator:
    autowire: true
    public: true
    arguments:
      $root: "%kernel.project_dir%"
      $satisFilename: "%satis_filename%"
      $composerHome: "%composer.home%"
